### ISSUE TITLE
Do http/s imposters need to set Connection: close?

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#113]
This used to be true to prevent clients from trying to reuse a socket that the server wasn't tracking any more, but with the close logic added to abstractServer which force closes all open sockets, I _think_ it's no longer needed.  It'd be nice to remove it because it's an unfortunate special case that can be unintuitive.

**Comment by matthid** [comment]
I'm actually hit by this. You cannot use NTLM authentication with mountebank because of this:
http://www.benjaminathawes.com/2010/10/14/ntlms-dependency-on-http-keep-alives-another-cause-of-the-dreaded-401-1-error/

Is there a workaround? I tried to disable all "connection: close" lines in the mountebank code but it did'nt seem to help.

- https://github.com/bbyars/mountebank/blob/7794bb8afc0a1195767879a688c7035f46f45c31/src/models/http/baseHttpServer.js#L58
- https://github.com/bbyars/mountebank/blob/95a5b41f1305bd19e18c07475948527a5e418e93/src/models/soap/soapServer.js#L36
- https://github.com/bbyars/mountebank/blob/ef069a06dbadfc163f32d6c02736a25866b167da/src/models/http/httpProxy.js#L55

**Comment by bbyars** [comment]
Commit 9821cdd added support for overriding the Connection header. I'm nervous of changing the default because I suspect it may change subtle errors in various test suites of people using mountebank, but the ability to override it explicitly allows us to test if those concerns are valid or not.

Will be part of the v1.7 release in a couple weeks. Until then, you can either use the code or one of the install options from the test site: http://mountebank-dev.herokuapp.com/docs/install
