### ISSUE TITLE
Mountebank is not shrinkwrap compatible

### ISSUE THREAD

**Issue by kutzi** [bbyars/mountebank#120]
When I add mountebank as dev dependency to my project, I cannot shrinkwrap the dependencies anymore.

i.e.

> ] npm shrinkwrap --dev
> (works fine)
> ] npm install mountebank --save-dev
> ] npm shrinkwrap --dev
> npm ERR! Error: Problems were encountered
> npm ERR! Please correct and try again.
> npm ERR! extraneous: abab@1.0.1 /home/ckutz/rwd/cara-boot/node_modules/mountebank/node_modules/abab
> npm ERR! extraneous: acorn-globals@1.0.9 /home/ckutz/rwd/cara-boot/node_modules/mountebank/node_modules/acorn-globals
> npm ERR! extraneous: browser-request@0.3.3 /home/ckutz/rwd/cara-boot/node_modules/mountebank/node_modules/browser-request
> npm ERR! extraneous: coffee-script@1.3.3 /home/ckutz/rwd/cara-boot/node_modules/mountebank/node_modules/coffee-script
> ...

**Comment by bbyars** [comment]
Thanks for reporting.  Do you have a project I can clone to test?  I'm unable to reproduce with grunt-mountebank (https://github.com/bbyars/grunt-mountebank).  The shrinkwrap file, including mountebank, is here:
https://github.com/bbyars/grunt-mountebank/blob/master/npm-shrinkwrap.json
-Brandon

**Comment by kutzi** [comment]
I can reproduce it with this example: https://github.com/kutzi/mountebank-shrinkwrap

**Comment by akalman** [comment]
This is actually a npm issue, not a bug in mountebank.  Mountebank is published using npm v3, which modifies the behavior of where npm dependencies are installed.  npm v2 does not expect this, and will throw errors because of it when trying to shrinkwrap.  Upgrading to npm v3 solves this issue.

If for some reason you are stuck on npm v2, there is an only moderately inconvenient workaround.  Add all of [mountebanks top level dependencies](https://github.com/bbyars/mountebank/blob/master/package.json#L60-L76) to your own package.json.  Then, between `npm install` and `npm shrinkwrap`, delete the `node_modules/mountebank/node_modules` folder.  This workaround works for grunt-mountebank, if you are using that as well.

For reference, upgrading to npm v3 only solved the issue for me if my version of mountebank is exactly `1.5.1`.  I still encountered problems for other versions (the problem varied by version) that I did not try to solve.

**Comment by bbyars** [comment]
Adam - thanks for the explanation. I'll add some docs on the next release
to this effect.
-Brandon

**Comment by delta62** [comment]
I just tried creating an NPM shrinkwrap file using npm 3 and I had this issue as well. Similar errors about extraneous packages.

- npm: 3.10.9
- mountebank: 1.8.0
