### ISSUE TITLE
Secure endpoints for mb

### ISSUE THREAD

**Issue by sledoux** [bbyars/mountebank#150]
We intend to host mountebank in a webapp so all of our service can use this stub. But is it possible to authenticate the calls made to mountebank in any way? If we can't, this would be a security issue and would make mb viable only if running locally.

Is there any form of authentication possible?

**Comment by bbyars** [comment]
Hi,
Also responded on the mailing list, but here it is:

I'm not quite sure I understood the question. Are you:

1) Trying to authenticate the mountebank admin port (default 2525) so that
only authenticated clients can set up stubs? or

2) Trying to authenticate an imposter on a different port?

The first isn't possible, but the second is with predicates. For instance,
you could set a stub with a predicate that looks at the Authorization
header or X-API-Key header and returns expected responses, and a second
stub (at the end of the stubs array) with no predicates that returns a 403
status code.
