### ISSUE TITLE
Quotes in strings incorrectly escaped.

### ISSUE THREAD

**Issue by martinhyldgaard** [bbyars/mountebank#178]
#### Expected behaviour

When POSTing then GETting an imposter, I expect the same functionality of the imposter

#### Actual behaviour

The imposter is in a state where it no longer returns valid json.

#### Steps to reproduce

POST this imposter:
```
{
  "protocol": "http",
  "port": 4555,
  "requests": [],
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/customers/123"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": {
              "Location": "http://localhost:4555/customers/123",
              "Content-Type": "application/json",
              "Connection": "close"
            },
            "body": "{\"object\":{\"stringWithQuote\":\"this is a \\\"test\\\"\"}}"
          }
        }
      ]
    },
    {
      "responses": [
        {
          "is": {
            "statusCode": 404
          }
        }
      ]
    }
  ],
  "_links": {
    "self": {
      "href": "http://127.0.0.1:2525/imposters/4555"
    }
  }
}
```

Then GET it again. The quotes in "test" are no longer escaped, if POSTed again invalid json is returned. This is the version returned by GET:

```
{
  "protocol": "http",
  "port": 4555,
  "numberOfRequests": 0,
  "requests": [],
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/customers/123"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": {
              "Location": "http://localhost:4555/customers/123",
              "Content-Type": "application/json",
              "Connection": "close"
            },
            "body": "{\"object\":{\"stringWithQuote\":\"this is a \"test\"\"}}"
          }
        }
      ]
    },
    {
      "responses": [
        {
          "is": {
            "statusCode": 404
          }
        }
      ]
    }
  ],
  "_links": {
    "self": {
      "href": "http://127.0.0.1:2525/imposters/4555"
    }
  }
}
```

#### Software versions used

```
OS         : ubuntu 16.04
mountebank : 1.7.2
node.js    : 6.9.1
  (only if installed via npm)
Installation method : npm
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
info: [mb:2525] mountebank v1.7.2 now taking orders - point your browser to http://localhost:2525 for help
debug: [mb:2525] config: {"options":{"noParse":false,"nologfile":false,"allowInjection":false,"mock":false,"debug":false,"removeProxies":false,"heroku":false,"version":false,"help":false,"loglevel":"debug","port":2525,"pidfile":"mb.pid","logfile":"mb.log","savefile":"mb.json"},"process":{"nodeVersion":"v6.9.1","architecture":"x64","platform":"linux"}}
info: [mb:2525] POST /imposters
debug: [mb:2525] ::ffff:127.0.0.1:58386 => {"protocol":"http","port":4555,"requests":[],"stubs":[{"predicates":[{"equals":{"method":"POST","path":"/customers/123"}}],"responses":[{"is":{"statusCode":201,"headers":{"Location":"http://localhost:4555/customers/123","Content-Type":"application/json","Connection":"close"},"body":"{\"object\":{\"stringWithQuote\":\"this is a \\\"test\\\"\"}}"}}]},{"responses":[{"is":{"statusCode":404}}]}],"_links":{"self":{"href":"http://127.0.0.1:2525/imposters/4555"}}}
info: [http:4555] Open for business...
info: [mb:2525] GET /imposters/4555

```

**Comment by bbyars** [comment]
Thanks for reporting (and for providing so many details). Can you confirm you're not doing something in your deserialization that's stripping the quotes? I tested both the latest code and v1.7.2 with the JSON you added to the issue (I used curl instead of any client code), and I get the quotes properly escaped on the subsequent GET, and can successfully rePOST it. A diff of what I POSTed and what I GET is below, which shows only differences that will be ignored when creating the imposter. It appears from the logs that there are no other hidden operations to worry about, which means it's either something specific to your environment or to the deserialization code you have, and the deserialization code probably be the easiest thing to spot.

Any additional observations you can make to help troubleshoot?

bbyars@ubuntu:~/src/test$ diff out.json test.json
4d3
<   "numberOfRequests": 0,
42c41
<       "href": "http://localhost:2525/imposters/4555"
---
>       "href": "http://127.0.0.1:2525/imposters/4555"
45c44
< }
\ No newline at end of file
---
> }

**Comment by martinhyldgaard** [comment]
Thanks for looking into it. It was, as you point out, something with the deserialization. I was using Postman, when using curl the escapes are as expected.

**Comment by bbyars** [comment]
Perfect - thanks for letting me know.
