### ISSUE TITLE
Allow proxy: disabled

### ISSUE THREAD

**Issue by ruudk** [bbyars/mountebank#312]
#### Expected behaviour

I want to set-up a proxy that is `disabled`. It will help future developer when they want to record some mocks. They can simple enable the proxy, so that it will pass traffic to the target. But by default, I want to have it `disabled` so that my tests never talk to a real API.

#### Actual behaviour

It still proxies.

## Would this be possible?

If so, I could create a PR to try it.

**Comment by bbyars** [comment]
Yep, happy to accept that as a PR. Makes sense to me.

**Comment by prasann** [comment]
I guess these are related https://github.com/bbyars/mountebank/issues/284?

**Comment by bbyars** [comment]
Related, but it sounds different. #284 is to enable mountebank to always call the downstream service but not to record the responses (avoiding a memory leak for long-lived test runs where only some of the responses need to be virtualized). This issue is to prevent a proxy from talking to the downstream services without a configuration change. That does raise some interesting design challenges that didn't occur to me before. Take the following stub config:

````
{
  "responses": [{
    "proxy": {
      "disabled": true,
      "to": "..."
    }
  }]
}
````
What happens? Use the default response (same as not adding any responses)? Now what about this:

````
{
  "responses": [
    {
      "proxy": {
        "disabled": true,
        "to": "..."
      }
    },
    {
      "is": { ... }
    }
  ]
}
````

Should it use the second response in the array? There are other possibilities, and it seems that deciding what happens in each is going to be a bit arbitrary, creating confusion on the usage. Given that, I think I'd prefer the restrict the ability to disable responses at the stub level, not the response level. Then it's very clear what happens, mountebank does not process that stub _in it's entirety_ when deciding how to respond:

````
{
  "protocol": "http",
  "port": 3000,
  "stubs": [
    {
      "disabled": true
    },
    {
      .... 
    }
  ]
}
````
