### ISSUE TITLE
How to use wire return when we use Behaviors in shellTransform？

### ISSUE THREAD

**Issue by sxqAegean** [bbyars/mountebank#465]
Hello, Afternoon！
I have one question to your help，
How to use wire return when we use Behaviors in shellTransform？
The official documentation write description：
The application should write to stdout a JSON representation of the transformed response, which will be passed to the next shell command in the list, or returned over the wire if not more transformations are needed.
but don't have wire demo。
please help me, thank you very much.

**Comment by bbyars** [comment]
Hi there,
There's a fully worked example here
<http://www.mbtest.org/docs/api/behaviors#behavior-shellTransform>. The
shell application takes in the JSON representation of the request &
response in environment variables, and writes the JSON response to stdout.
So, for example, your shell application could write the following to stdout:

{ "statusCode": 400, "body": "Invalid input" }

In the absence of other behaviors or shell transforms, that output would
directly translate to the wire output.
-Brandon

**Comment by sxqAegean** [comment]
First, Thanks for you help！ 
Second, The exmple in  <http://www.mbtest.org/docs/api/behaviors#behavior-shellTransform> that is "http" protocol . 
I want to know how to use it with "tcp" protocol.
Thank you very much.
Good night!

**Comment by bbyars** [comment]
Hi,
The only difference is the JSON format of the request & response, which are
documented under the HTTP Requests and Responses
<http://www.mbtest.org/docs/protocols/http> header on the linked page and TCP
Request and Reponse <http://www.mbtest.org/docs/protocols/tcp> header.
Since TCP is more a transport protocol than an application protocol, it has
a more generic format, where effectively both the request and the response
have only a single field

{ "data": "the payload" }

All the rest of the code is the same.
-Brandon
