### ISSUE TITLE
Feature request: Support configFile retrieval via HTTP

### ISSUE THREAD

**Issue by SokratisVidros** [bbyars/mountebank#498]
Hi,

I was wondering whether mountebank can support fetching configFiles for imposters and stubs via HTTP. That way, configFiles could be retrieved from FTP servers, Github repositories, etc...

Does that make sense?

Thank you in advance.

**Comment by bbyars** [comment]
Hi there,
To make sure I understand, are you referring to the EJS templates you pass
into the --configfile command line option?
-Brandon

**Comment by SokratisVidros** [comment]
That's right.

**Comment by bbyars** [comment]
Thanks for the clarification. It's tricky because of the way you include
other files. So, for instance, a top-level config file includes
'stubs/first.ejs', which includes 'stubs/responses/first.ejs', which
includes 'stubs/responses/injections/first.js'. Are you envisioning
something like:

> mb --configfile http://network-share.com/configfiles/top-level.ejs

And then have mountebank automatically make subsequent calls to
http://network-share.com/configfiles/stubs/first.ejs,
http://network-share.com/configfiles/stubs/responses/first.ejs, and
http://network-share.com/configfiles/stubs/responses/injections/first.ejs?

Similarly, what about a top-level config that includes "../../stubs.ejs".
How would you expect mountebank to handle that given the same command line
above?
-Brandon

**Comment by SokratisVidros** [comment]
The proposal would only work for a single file for simple mountebank configurations. I agree that is quite limiting and the full blown requires a completely different solution if needed.

**Comment by bbyars** [comment]
Unfortunately I think practically speaking, making this work in a general purpose fashion is too complicated to justify the cost. My hope is the new --datadir CLI flag allows a better way to navigate the test data, and upcoming #177 allows for formatting flexibility.
